const data = {
    products: [
        {
            _id: '1',
            name: 'White Button Up Shirt',
            category: 'Shirt',
            image: 'images/p1.jpeg',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'Adidas Tee Shirt',
            category: 'Shirt',
            image: 'images/p2.jpeg',
            price: 100,
            brand: 'Adidas',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'Lacoste Polo Shirt',
            category: 'Shirt',
            image: 'images/p3.jpeg',
            price: 220,
            brand: 'Lacoste',
            rating: 4.8,
            numReviews: 17,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'Nike Slim Pant',
            category: 'Pants',
            image: 'images/p4.jpeg',
            price: 78,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 14,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'Puma Soccer Shorts',
            category: 'Pants',
            image: 'images/p5.jpeg',
            price: 65,
            brand: 'Puma',
            rating: 4.2,
            numReviews: 20,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Adidas Leggings',
            category: 'Pants',
            image: 'images/p6.jpeg',
            price: 139,
            brand: 'Adidas',
            rating: 4.7,
            numReviews: 15,
            description: 'high quality product',
        },
    ],
};
export default data;